### ISSUE TITLE
Remove at-mixin-pattern rule for external use

### ISSUE THREAD

**Issue by TheSavageDev** [cerner/stylelint-config-terra#26]
# Issue Description

The rule in stylelint.config.js
```js
'scss/at-mixin-pattern': '^(terra-)[a-z]+([a-z0-9-]+[a-z0-9]+)?$',
```
Requires external users to preface their mixins with `terra-`

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

No error should be thrown when not using the `terra-` prefix.

## Current Behavior

Running stylelint with a mixin without `terra-` causes an error to be thrown

## Steps to Reproduce

1. Create a mixin without the prefix of `terra-`
2. Run `npm run lint:scss`

## Environment

* Version: 2.0.0
* Browser Name and Version: N/A
* Operating System and version (desktop or mobile): MacOS Mojave

## @ Mentions

@bjankord

**Comment by bjankord** [comment]
Talked about defaulting these rules to off and then turning them on in the monorepos.
