### ISSUE TITLE
Remove the "terra-*" Prefix Requirement for Linter Variables

### ISSUE THREAD

**Issue by andrewnottaviano** [cerner/stylelint-config-terra#42]
# Bug Report

## Description

When adding a theme in our project, we have to silence the linter because we don't want to add "terra-*" to the front of our scss variable names. As a consumer, I don't think we want to make our variables seem to be linked to terra styles. (see https://github.com/cerner/stylelint-config-terra/blob/afe907d84f11ae648a1fed3ac7053f1b61ddfd1e/stylelint.config.js#L18)
## Steps to Reproduce

1. Create a theme in a consuming project.
2. Add some variables for your theme.
3. Observe the linter rule failure.

## Expected Behavior

An error should not be thrown if we do not have "terra-*" in our variable names.
## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions

@StephenEsser

**Comment by ryanthemanuel** [comment]
@andrewnottaviano is this something you would want to contribute?
